function demo(){var cb='',_=' top: -1000px;',zb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',ib='");',Ab='#',Pc='.cache.js',Cb='/',Ib='//',qc='03B3A288DA1840486F231EF37EF1C41D',uc='687A70B2512549A577E98795D3E8E8BE',vc='7472543874AED1E5B4543A29C17D3F55',Oc=':',rc=':1',Cc=':10',Dc=':11',Ec=':12',Fc=':13',Gc=':14',Hc=':15',Ic=':16',Jc=':17',Kc=':18',Lc=':19',sc=':2',tc=':3',wc=':4',xc=':5',yc=':6',zc=':7',Mc=':8',Nc=':9',rb='::',ad=':moduleBase',bb='<!doctype html>',db='<html><head><\/head><body><\/body><\/html>',ub='=',Bb='?',wb='Bad handler "',ab='CSS1Compat',gb='Chrome',Ac='DC60336F39434E494847BABADA49A258',fb='DOMContentLoaded',W='DUMMY',Bc='E55F153276A75F454BCF1C42E42B7EF8',_c='Ignoring non-whitelisted Dev Mode URL: ',$c='__gwtDevModeHook:demo',Zc='_gwt_dummy_',cc='adobeair',dc='air',Hb='base',Fb='baseUrl',R='begin',X='body',Q='bootstrap',Kb='chrome',Eb='clear.cache.gif',tb='content',U='demo',pc='demo.devmode.js',Gb='demo.nocache.js',qb='demo::',Wc='end',hb='eval("',Yc='file:',$b='gecko',ac='gecko1_8',bc='gecko1_9',S='gwt.codesvr.demo=',T='gwt.codesvr=',yb='gwt:onLoadErrorFn',vb='gwt:onPropertyErrorFn',sb='gwt:property',Jb='gxt.user.agent',nb='head',Tc='href',Xc='http:',Nb='ie10',Tb='ie6',Rb='ie7',Pb='ie8',Ob='ie9',Y='iframe',Db='img',kb='javascript',Z='javascript:""',Qc='link',lc='linux',Uc='loadExternalRefs',kc='mac',jc='mac os x',ic='macintosh',ob='meta',mb='moduleRequested',lb='moduleStartup',Mb='msie',Sb='msie 6',Qb='msie 7',pb='name',Lb='opera',$='position:absolute; width:0; height:0; border:none; left: -1000px;',Rc='rel',Vc='reset.css',_b='rv:1.8',Ub='safari',Wb='safari3',Yb='safari4',Zb='safari5',jb='script',oc='selectingPermutation',V='startup',Sc='stylesheet',eb='undefined',gc='unknown',ec='user.agent',hc='user.agent.os',Vb='version/3',Xb='version/4',fc='webkit',nc='win32',mc='windows';var o=window;var p=document;r(Q,R);function q(){var a=o.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:U,sessionId:o.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
demo.__sendStats=r;demo.__moduleName=U;demo.__errFn=null;demo.__moduleBase=W;demo.__softPermutationId=0;demo.__computePropValue=null;demo.__getPropMap=null;demo.__gwtInstallCode=function(){};demo.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[U]={moduleName:U};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(X)[0]}
function B(){if(v){return}var a=p.createElement(Y);a.src=Z;a.id=U;a.style.cssText=$+_;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==ab?bb:cb;v.write(b+db);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==eb){return typeof p.body!=eb&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(fb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(fb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(hb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ib));g=f.createElement(jb);g.language=kb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(jb);g.language=kb;g.text=c[i];e.appendChild(g);d(e,g)}}}
demo.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;p.getElementsByTagName(nb)[0].appendChild(n)}
demo.__startLoadingFragment=function(a){return G(a)};demo.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(jb);c.language=kb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(ob);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(pb),k;if(j){j=j.replace(qb,cb);if(j.indexOf(rb)>=0){continue}if(j==sb){k=i.getAttribute(tb);if(k){var l,m=k.indexOf(ub);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=cb}c[j]=l}}else if(j==vb){k=i.getAttribute(tb);if(k){try{d=eval(k)}catch(a){alert(wb+k+xb)}}}else if(j==yb){k=i.getAttribute(tb);if(k){try{e=eval(k)}catch(a){alert(wb+k+zb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;demo.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Ab);if(b==-1){b=a.length}var c=a.indexOf(Bb);if(c==-1){c=a.length}var d=a.lastIndexOf(Cb,Math.min(c,b));return d>=0?a.substring(0,d+1):cb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Db);b.src=a+Eb;a=e(b.src)}return a}
function g(){var a=t(Fb);if(a!=null){return a}return cb}
function h(){var a=p.getElementsByTagName(jb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Gb)!=-1){return e(a[b].src)}}return cb}
function i(){var a=p.getElementsByTagName(Hb);if(a.length>0){return a[a.length-1].href}return cb}
function j(){var a=p.location;return a.href==a.protocol+Ib+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==cb){k=h()}if(k==cb){k=i()}if(k==cb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return demo.__moduleBase+a}
function H(){var f=[];var g=0;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[Jb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Kb)!=-1)return Kb;if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1){if(p.documentMode>=10)return Nb;if(p.documentMode>=9)return Ob;if(p.documentMode>=8)return Pb;if(a.indexOf(Qb)!=-1)return Rb;if(a.indexOf(Sb)!=-1)return Tb;return Nb}if(a.indexOf(Ub)!=-1){if(a.indexOf(Vb)!=-1)return Wb;if(a.indexOf(Xb)!=-1)return Yb;return Zb}if(a.indexOf($b)!=-1){if(a.indexOf(_b)!=-1)return ac;return bc}if(a.indexOf(cc)!=-1)return dc;return null};i[Jb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};j[ec]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(fc)!=-1}())return Ub;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=10}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=9}())return Ob;if(function(){return b.indexOf(Mb)!=-1&&p.documentMode>=8}())return Pb;if(function(){return b.indexOf($b)!=-1}())return ac;return gc};i[ec]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};j[hc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(ic)!=-1||a.indexOf(jc)!=-1){return kc}if(a.indexOf(lc)!=-1){return lc}if(a.indexOf(mc)!=-1||a.indexOf(nc)!=-1){return mc}return gc};i[hc]={linux:0,mac:1,unknown:2,windows:3};s=function(a,b){return b in i[a]};demo.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};demo.__computePropValue=k;o.__gwt_activeModules[U].bindings=demo.__getPropMap;r(Q,oc);if(q()){return G(pc)}var l;try{h([Ob,Ob,lc],qc);h([Ob,Ob,kc],qc+rc);h([Ob,Ob,gc],qc+sc);h([Ob,Ob,mc],qc+tc);h([Nb,Nb,lc],uc);h([Nb,Nb,kc],uc+rc);h([Nb,Nb,gc],uc+sc);h([Nb,Nb,mc],uc+tc);h([ac,ac,lc],vc);h([ac,ac,kc],vc+rc);h([ac,ac,gc],vc+sc);h([ac,ac,mc],vc+tc);h([bc,ac,lc],vc+wc);h([bc,ac,kc],vc+xc);h([bc,ac,gc],vc+yc);h([bc,ac,mc],vc+zc);h([Pb,Pb,lc],Ac);h([Pb,Pb,kc],Ac+rc);h([Pb,Pb,gc],Ac+sc);h([Pb,Pb,mc],Ac+tc);h([dc,Ub,lc],Bc);h([dc,Ub,kc],Bc+rc);h([Wb,Ub,gc],Bc+Cc);h([Wb,Ub,mc],Bc+Dc);h([Yb,Ub,lc],Bc+Ec);h([Yb,Ub,kc],Bc+Fc);h([Yb,Ub,gc],Bc+Gc);h([Yb,Ub,mc],Bc+Hc);h([Zb,Ub,lc],Bc+Ic);h([Zb,Ub,kc],Bc+Jc);h([Zb,Ub,gc],Bc+Kc);h([Zb,Ub,mc],Bc+Lc);h([dc,Ub,gc],Bc+sc);h([dc,Ub,mc],Bc+tc);h([Kb,Ub,lc],Bc+wc);h([Kb,Ub,kc],Bc+xc);h([Kb,Ub,gc],Bc+yc);h([Kb,Ub,mc],Bc+zc);h([Wb,Ub,lc],Bc+Mc);h([Wb,Ub,kc],Bc+Nc);l=f[k(Jb)][k(ec)][k(hc)];var m=l.indexOf(Oc);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}demo.__softPermutationId=g;return G(l+Pc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Qc);b.setAttribute(Rc,Sc);b.setAttribute(Tc,G(a));p.getElementsByTagName(nb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Uc,R);c(Vc);r(Uc,Wc)}
D();demo.__moduleBase=F();u[U].moduleBase=demo.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==Xc||o.location.protocol==Yc);o.__gwt_activeModules[U].canRedirect=K;function L(){var b=Zc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=$c;var N=o.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(_c+N)}N=cb}if(N&&!o[M]){o[M]=true;o[M+ad]=F();var O=p.createElement(jb);O.src=N;var P=p.getElementsByTagName(nb)[0];P.insertBefore(O,P.firstElementChild||P.children[0]);return false}}}I();r(Q,Wc);C(J);return true}
demo.succeeded=demo();